import type { ClothingItem } from './types';
import { PlaceHolderImages } from './placeholder-images';

const getImage = (id: string) => PlaceHolderImages.find(img => img.id === id)?.imageUrl || '';

export const mockClothingItems: ClothingItem[] = [
  { id: '1', userId: 'user1', imageUrl: 'https://firebasestorage.googleapis.com/v0/b/studio-2998395971-59cfc.appspot.com/o/defaults%2Fclassic-white-tee.png?alt=media', color: 'White', fabric: 'Cotton', pattern: 'Solid', season: 'Summer', length: 'Long', category: 'Top', occasion: 'Casual', description: 'Classic White Tee', lastWorn: '2023-10-15', formal: 2, warmth: 1, relaxed: 10 },
  { id: '2', userId: 'user1', imageUrl: 'https://firebasestorage.googleapis.com/v0/b/studio-2998395971-59cfc.appspot.com/o/defaults%2Fcozy-black-hoodie.png?alt=media', color: 'Black', fabric: 'Fleece', pattern: 'Solid', season: 'Winter', length: 'Long', category: 'Outerwear', occasion: 'Casual', description: 'Cozy Black Hoodie', lastWorn: '2023-10-20', formal: 1, warmth: 7, relaxed: 9 },
  { id: '3', userId: 'user1', imageUrl: 'https://firebasestorage.googleapis.com/v0/b/studio-2998395971-59cfc.appspot.com/o/defaults%2Fstandard-blue-jeans.png?alt=media', color: 'Blue', fabric: 'Denim', pattern: 'Solid', season: 'Autumn', length: 'Long', category: 'Bottom', occasion: 'Casual', description: 'Standard Blue Jeans', lastWorn: null, formal: 4, warmth: 5, relaxed: 6 },
  { id: '4', userId: 'user1', imageUrl: 'https://firebasestorage.googleapis.com/v0/b/studio-2998395971-59cfc.appspot.com/o/defaults%2Foffice-chinos.png?alt=media', color: 'Beige', fabric: 'Cotton Twill', pattern: 'Solid', season: 'Spring', length: 'Long', category: 'Bottom', occasion: 'Business', description: 'Office Chinos', lastWorn: '2023-09-01', formal: 8, warmth: 3, relaxed: 5 },
  { id: '5', userId: 'user1', imageUrl: 'https://firebasestorage.googleapis.com/v0/b/studio-2998395971-59cfc.appspot.com/o/defaults%2Fstreet-sneakers.png?alt=media', color: 'White', fabric: 'Leather', pattern: 'Solid', season: 'Spring', length: 'Long', category: 'Shoes', occasion: 'Casual', description: 'Street Sneakers', lastWorn: null, formal: 3, warmth: 4, relaxed: 9 },
  { id: '6', userId: 'user1', imageUrl: 'https://firebasestorage.googleapis.com/v0/b/studio-2998395971-59cfc.appspot.com/o/defaults%2Fwinter-boots.png?alt=media', color: 'Brown', fabric: 'Leather', pattern: 'Solid', season: 'Winter', length: 'Long', category: 'Shoes', occasion: 'Everyday', description: 'Winter Boots', lastWorn: '2023-10-22', formal: 5, warmth: 9, relaxed: 4 },
  { id: '7', userId: 'user1', imageUrl: 'https://firebasestorage.googleapis.com/v0/b/studio-2998395971-59cfc.appspot.com/o/defaults%2Fvintage-jacket.png?alt=media', color: 'Brown', fabric: 'Denim', pattern: 'Solid', season: 'Autumn', length: 'Long', category: 'Outerwear', occasion: 'Casual', description: 'Vintage Jacket', lastWorn: '2023-10-28', formal: 2, warmth: 6, relaxed: 8 },
  { id: '8', userId: 'user1', imageUrl: 'https://firebasestorage.googleapis.com/v0/b/studio-2998395971-59cfc.appspot.com/o/defaults%2Foxford-shirt.png?alt=media', color: 'Blue', fabric: 'Cotton', pattern: 'Solid', season: 'Spring', length: 'Long', category: 'Top', occasion: 'Business', description: 'Oxford Shirt', lastWorn: '2023-08-15', formal: 9, warmth: 2, relaxed: 3 },
  { id: '9', userId: 'user1', imageUrl: getImage('item10'), color: 'Brown', fabric: 'Leather', pattern: 'Solid', season: 'Autumn', length: 'Long', category: 'Accessory', occasion: 'Everyday', description: 'Brown Leather Crossbody Bag', lastWorn: null, formal: 4, warmth: 3, relaxed: 7 },
  { id: '10', userId: 'user1', imageUrl: getImage('item11'), color: 'Blue', fabric: 'Denim', pattern: 'Solid', season: 'Spring', length: 'Long', category: 'Outerwear', occasion: 'Casual', description: 'Classic Denim Jacket', lastWorn: '2023-10-18', formal: 2, warmth: 4, relaxed: 8 },
  { id: '11', userId: 'user1', imageUrl: getImage('item13'), color: 'Gold', fabric: 'Metal', pattern: 'Solid', season: 'Spring', length: 'Long', category: 'Accessory', occasion: 'Party', description: 'Gold Statement Necklace', lastWorn: null, formal: 7, warmth: 0, relaxed: 2 },
  { id: '12', userId: 'user1', imageUrl: getImage('item14'), color: 'Pink', fabric: 'Satin', pattern: 'Solid', season: 'Summer', length: 'Midi', category: 'Bottom', occasion: 'Party', description: 'Pink Satin Midi Skirt', lastWorn: '2023-07-20', formal: 8, warmth: 2, relaxed: 4 },
];
